Repository ZupIT/ritchie-cli, pull requests merged in 2020-07, with the labels that each got.

#215 [FIX] improvements rit upgrade
  cmd/single/main.go
  cmd/team/main.go
  pkg/api/api.go
  pkg/cmd/root.go
  pkg/cmd/upgrade.go
  pkg/cmd/upgrade_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/version/resolver.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: improvement

#236 [FEATURE] Change Login and Init behavior
  cmd/team/main.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/login.go
  pkg/cmd/login_test.go
  pkg/cmd/mocks_test.go
  pkg/security/otp/otp.go
  pkg/security/otp/otp_test.go
  pkg/security/otp/resolver.go
  pkg/server/server.go
  pkg/server/setter.go
  pkg/server/setter_test.go
  testdata/stubby4j/integrations.yml
Labels: feature

#233 [FEATURE] survey prompt
  README.md
  cmd/single/main.go
  cmd/team/main.go
  functional/runner.go
  functional/runner_unix.go
  functional/single/core/core_integration_test.go
  functional/single/init/init_feature.json
  functional/single/init/init_integration_test.go
  functional/single/scaffold/scaffold_integration_test.go
  functional/team/core/core_integration_test.go
  go.mod
  pkg/cmd/create_formula.go
  pkg/cmd/delete_context.go
  pkg/cmd/init_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/formula/runner/default_runner_test.go
  pkg/prompt/bool.go
  pkg/prompt/email.go
  pkg/prompt/int.go
  pkg/prompt/list.go
  pkg/prompt/multiline.go
  pkg/prompt/password.go
  pkg/prompt/prompt.go
  pkg/prompt/text.go
  pkg/prompt/url.go
  pkg/validator/validator.go
Labels: feature

#242 [DEPRECATION] Remove `rit clean repo` command
  cmd/single/main.go
  cmd/team/main.go
  functional/single/core/core_feature.json
  functional/single/core/core_integration_test.go
  functional/single/init/init_feature.json
  functional/single/init/init_integration_test.go
  functional/single/stdin/stdin_feature.json
  functional/single/stdin/stdin_integration_test.go
  functional/team/core/core_feature.json
  functional/team/core/core_integration_test.go
  pkg/api/api.go
  pkg/cmd/clean.go
  pkg/cmd/clean_repo.go
  pkg/cmd/clean_repo_test.go
  pkg/cmd/clean_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/repo.go
  pkg/formula/repo/default_repo.go
Labels: deprecation

#246 [DEPRECATION] Removed rit clean repo
  cmd/single/main.go
  cmd/team/main.go
  functional/single/core/core_feature.json
  functional/single/core/core_integration_test.go
  functional/single/init/init_feature.json
  functional/single/init/init_integration_test.go
  functional/single/stdin/stdin_feature.json
  functional/single/stdin/stdin_integration_test.go
  functional/team/core/core_feature.json
  functional/team/core/core_integration_test.go
  pkg/api/api.go
  pkg/cmd/clean.go
  pkg/cmd/clean_repo.go
  pkg/cmd/clean_repo_test.go
  pkg/cmd/clean_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/repo.go
  pkg/formula/repo/default_repo.go
Labels: deprecation

#245 Improvement/rit completion
  cmd/single/main.go
  cmd/team/main.go
  pkg/autocomplete/autocomplete.go
  pkg/autocomplete/generator.go
  pkg/autocomplete/generator_test.go
  pkg/cmd/autocomplete.go
  pkg/cmd/autocomplete_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/root.go
Labels: improvement

#241 [FEATURE] List and add on set credentials
  cmd/single/main.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/credential/credential.go
  pkg/credential/credsingle/settings.go
  pkg/credential/credsingle/settings_test.go
  testdata/credentials.json
Labels: feature, single

#260 [FEATURE] Added `rit set priority` command
  cmd/single/main.go
  cmd/team/main.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_priority.go
  pkg/cmd/set_priority_test.go
  pkg/formula/repo.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/priority_setter.go
Labels: feature

#266 Added `rit list repo` command
  cmd/single/main.go
  cmd/team/main.go
  go.mod
  pkg/cmd/list_repo.go
  vendor/github.com/docker/docker/pkg/urlutil/urlutil.go
  vendor/github.com/gofrs/flock/.gitignore
  vendor/github.com/gofrs/flock/.travis.yml
  vendor/github.com/gofrs/flock/LICENSE
  vendor/github.com/gofrs/flock/README.md
  vendor/github.com/gofrs/flock/appveyor.yml
  vendor/github.com/gofrs/flock/flock.go
  vendor/github.com/gofrs/flock/flock_unix.go
  vendor/github.com/gofrs/flock/flock_winapi.go
  vendor/github.com/gofrs/flock/flock_windows.go
  vendor/modules.txt
Labels: feature

#250 Feature/verbose flag
  pkg/cmd/build_test.go
  pkg/cmd/formulas.go
  pkg/cmd/mocks_test.go
  pkg/crypto/cryptoutil/crypto_util_test.go
  pkg/formula/creator/creator_test.go
  pkg/formula/formula.go
  pkg/formula/runner/default_runner.go
  pkg/formula/runner/default_runner_test.go
  pkg/formula/runner/docker_runner.go
  pkg/formula/runner/docker_runner_test.go
  pkg/formula/runner/inputs_test.go
Labels: feature

#268 [FEATURE] Added `rit delete repo` command and added to list repo a total info a…
  cmd/single/main.go
  pkg/cmd/delete_repo.go
  pkg/cmd/list_repo.go
  pkg/formula/repo/deleter.go
  pkg/formula/repo/lister.go
Labels: feature

#272 [FEATURE] Create command to update repositories
  cmd/single/main.go
  cmd/team/main.go
  go.mod
  pkg/api/api.go
  pkg/cmd/add_repo.go
  pkg/cmd/delete_repo.go
  pkg/cmd/set_priority.go
  pkg/cmd/update_repo.go
  pkg/formula/repo.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/creator.go
  pkg/formula/repo/deleter.go
  pkg/formula/repo/list_adder.go
  pkg/formula/repo/list_creator.go
  pkg/formula/repo/list_updater.go
  pkg/formula/repo/priority_setter.go
  pkg/formula/repo/updater.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/generator.go
  pkg/github/github.go
  pkg/github/repository.go
  pkg/prompt/int.go
  pkg/prompt/prompt.go
  vendor/github.com/thoas/go-funk/.gitignore
  vendor/github.com/thoas/go-funk/.travis.yml
  vendor/github.com/thoas/go-funk/CHANGELOG.md
  vendor/github.com/thoas/go-funk/LICENSE
  vendor/github.com/thoas/go-funk/Makefile
  vendor/github.com/thoas/go-funk/README.rst
  vendor/github.com/thoas/go-funk/builder.go
  vendor/github.com/thoas/go-funk/chain_builder.go
  vendor/github.com/thoas/go-funk/compact.go
  vendor/github.com/thoas/go-funk/fill.go
  vendor/github.com/thoas/go-funk/go.mod
  vendor/github.com/thoas/go-funk/go.sum
  vendor/github.com/thoas/go-funk/helpers.go
  vendor/github.com/thoas/go-funk/intersection.go
  vendor/github.com/thoas/go-funk/lazy_builder.go
  vendor/github.com/thoas/go-funk/map.go
  vendor/github.com/thoas/go-funk/max.go
  vendor/github.com/thoas/go-funk/min.go
  vendor/github.com/thoas/go-funk/operation.go
  vendor/github.com/thoas/go-funk/presence.go
  vendor/github.com/thoas/go-funk/reduce.go
  vendor/github.com/thoas/go-funk/retrieve.go
  vendor/github.com/thoas/go-funk/scan.go
  vendor/github.com/thoas/go-funk/subtraction.go
  vendor/github.com/thoas/go-funk/transform.go
  vendor/github.com/thoas/go-funk/typesafe.go
  vendor/github.com/thoas/go-funk/utils.go
  vendor/github.com/thoas/go-funk/zip.go
  vendor/modules.txt
Labels: feature

#278 [DEPRECATION] Removed `rit clean repo` command
  cmd/single/main.go
  cmd/team/main.go
  functional/single/core/core_feature.json
  functional/single/core/core_integration_test.go
  functional/single/init/init_feature.json
  functional/single/init/init_integration_test.go
  functional/single/stdin/stdin_feature.json
  functional/single/stdin/stdin_integration_test.go
  functional/team/core/core_feature.json
  functional/team/core/core_integration_test.go
  pkg/api/api.go
  pkg/cmd/clean.go
  pkg/cmd/clean_repo.go
  pkg/cmd/clean_repo_test.go
  pkg/cmd/clean_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/repo.go
  pkg/formula/repo/default_repo.go
Labels: deprecation

#240 Fix formula path separator based on os
  pkg/cmd/formulas_test.go
  pkg/cmd/init_test.go
  pkg/formula/formula.go
  pkg/formula/formula_test.go
  pkg/formula/runner/default_setup_test.go
Labels: bug

#287 Add files entry to `set credential` command
  cmd/single/main.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/credential/credsingle/settings.go
Labels: feature

#294 adding powershell and fish and modifying helpers
  pkg/api/api.go
  pkg/cmd/autocomplete.go
Labels: bug

#277 Support templates to create formula
  cmd/main.go
  pkg/cmd/create_formula.go
  pkg/formula/builder/build.go
  pkg/formula/creator/creator.go
  pkg/formula/creator/creator_test.go
  pkg/formula/creator/lang/golang/golang.go
  pkg/formula/creator/lang/golang/template/template.go
  pkg/formula/creator/lang/java/java.go
  pkg/formula/creator/lang/java/template/template.go
  pkg/formula/creator/lang/node/node.go
  pkg/formula/creator/lang/node/template/template.go
  pkg/formula/creator/lang/php/php.go
  pkg/formula/creator/lang/php/template/template.go
  pkg/formula/creator/lang/python/python.go
  pkg/formula/creator/lang/python/template/template.go
  pkg/formula/creator/lang/shell/shell.go
  pkg/formula/creator/lang/shell/template/template.go
  pkg/formula/creator/lang/template/default.go
  pkg/formula/creator/template/default.go
  pkg/formula/creator/template/manager.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
  testdata/repos/commons/templates/create_formula/languages/bash shell/Makefile
  testdata/repos/commons/templates/create_formula/languages/bash shell/config.json
  testdata/repos/commons/templates/create_formula/languages/bash shell/src/hello/hello.sh
  testdata/repos/commons/templates/create_formula/languages/bash shell/src/main.sh
  testdata/repos/commons/templates/create_formula/languages/go/Dockerfile
  testdata/repos/commons/templates/create_formula/languages/go/Makefile
  testdata/repos/commons/templates/create_formula/languages/go/config.json
  testdata/repos/commons/templates/create_formula/languages/go/src/go.mod
  testdata/repos/commons/templates/create_formula/languages/go/src/go.sum
  testdata/repos/commons/templates/create_formula/languages/go/src/main.go
  testdata/repos/commons/templates/create_formula/languages/go/src/pkg/hello/hello.go
  testdata/repos/commons/templates/create_formula/languages/go/src/pkg/hello/hello_test.go
  testdata/repos/commons/templates/create_formula/languages/java/Makefile
  testdata/repos/commons/templates/create_formula/languages/java/config.json
  testdata/repos/commons/templates/create_formula/languages/java/pom.xml
  testdata/repos/commons/templates/create_formula/languages/java/src/main/java/com/ritchie/Main.java
  testdata/repos/commons/templates/create_formula/languages/java/src/main/java/com/ritchie/formula/Hello.java
  testdata/repos/commons/templates/create_formula/languages/java/src/test/java/com/ritchie/formula/HelloTest.java
  testdata/repos/commons/templates/create_formula/languages/node/Makefile
  testdata/repos/commons/templates/create_formula/languages/node/config.json
  testdata/repos/commons/templates/create_formula/languages/node/src/hello/hello.js
  testdata/repos/commons/templates/create_formula/languages/node/src/index.js
  testdata/repos/commons/templates/create_formula/languages/node/src/package.json
  testdata/repos/commons/templates/create_formula/languages/python/Makefile
  testdata/repos/commons/templates/create_formula/languages/python/config.json
  testdata/repos/commons/templates/create_formula/languages/python/src/hello/hello.py
  testdata/repos/commons/templates/create_formula/languages/python/src/main.py
  testdata/repos/commons/templates/create_formula/root/.gitignore
  testdata/repos/commons/templates/create_formula/root/README.md
  testdata/repos/commons/templates/create_formula/root/docs/img/ritchie-banner.png
Labels: 2.0.0, improvement

#292 [Suggest] Pull review guidelines according to last meeting
  CONTRIBUTING.md
Labels: documentation

#298 Fix tmp bin dir pattern
  pkg/formula/formula.go
Labels: bug

#288 Clean formulas command
  cmd/single/main.go
  cmd/team/main.go
  pkg/cmd/clean.go
  pkg/cmd/clean_formulas.go
  pkg/cmd/clean_formulas_test.go
  pkg/cmd/clean_test.go
  pkg/stdin/stdin.go
  pkg/stdin/stdin_test.go
Labels: feature

#301 added clean autocompletion
  pkg/api/api.go
Labels: 1.0.0, bug

#296 Fix tests and code style for lint
  .circleci/config.yml
  docker-compose.yml
  pkg/autocomplete/generator_test.go
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/init_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/cmd/set_priority_test.go
  pkg/cmd/upgrade_test.go
  pkg/credential/credsingle/finder_test.go
  pkg/credential/credsingle/setter_test.go
  pkg/formula/builder/build_test.go
  pkg/formula/formula_test.go
  pkg/formula/repo/priority_setter.go
  pkg/formula/runner/default_runner_test.go
  pkg/formula/runner/default_setup_test.go
  pkg/formula/runner/docker_runner_test.go
  pkg/formula/runner/inputs_test.go
  pkg/formula/tree/generator_test.go
  pkg/formula/watcher/watcher_test.go
  pkg/upgrade/url_finder.go
  pkg/upgrade/url_finder_test.go
  run-tests-ci.sh
  run-tests.sh
  testdata/nginx/certs/local.crt
  testdata/nginx/certs/local.key
  testdata/nginx/conf/nginx.conf
  testdata/ritchie-formulas-test.zip
  testdata/run-mock.bat
  testdata/run-mock.sh
  testdata/stubby4j/integrations.yml
  testdata/stubby4j/response.zip
  testdata/stubby4j/ritchie-formulas.zip
Labels: 2.0.0, improvement

#308 Change functional tests
  functional/core/core_integration_test.go
  functional/init/init_feature.json
  functional/init/init_integration_test.go
  functional/stdin/stdin_feature.json
  pkg/cmd/delete_repo.go
  pkg/cmd/root.go
Labels: 2.0.0, improvement

#306 Improvement/repo priority setter test
  cmd/main.go
  pkg/formula/repo/priority_setter.go
  pkg/formula/repo/priority_setter_test.go
Labels: 2.0.0, improvement

#309 Change Upgrade and CommonsUrl
  pkg/cmd/init.go
  pkg/upgrade/updater.go
  pkg/upgrade/url_finder_test.go
Labels: 2.0.0, improvement

#307 [FIX] Fix build formula on Windows
  pkg/formula/builder/build.go
  pkg/formula/builder/build_test.go
  pkg/formula/creator/lang/java/template/template.go
  pkg/stream/dir.go
Labels: 1.0.0, WIP, Windows, bug, priority:high, single, team

#305 Improvement/repo test
  pkg/cmd/add_repo.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/delete_test.go
  pkg/cmd/list_repo_test.go
  pkg/cmd/list_test.go
  pkg/formula/repo/adder_test.go
  pkg/formula/repo/creator.go
  pkg/formula/repo/creator_test.go
  pkg/formula/repo/deleter_test.go
  pkg/formula/repo/list_adder_test.go
  pkg/formula/repo/list_creator_test.go
  pkg/formula/repo/list_updater_test.go
  pkg/formula/repo/lister_test.go
  pkg/formula/repo/updater_test.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/github/repository.go
  pkg/github/repository_test.go
  testdata/ritchie-formulas.zip
Labels: 2.0.0, improvement

#239 Vulnerability SSL pipeline blocking ignored
  .circleci/config.yml
  cmd/team/main.go
  pkg/server/setter.go
Labels: bug

#313 [Fix] Credential AWS Provider Default
  pkg/credential/credsingle/settings.go
Labels: 1.0.0, bug, priority:high, single

#304 Create journey tips
  cmd/main.go
  pkg/api/api.go
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/build_formula.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/list_repo.go
  pkg/cmd/mocks_test.go
  pkg/cmd/root.go
  pkg/cmd/tutorial.go
  pkg/cmd/tutorial_test.go
  pkg/rtutorial/find_setter.go
  pkg/rtutorial/finder.go
  pkg/rtutorial/finder_test.go
  pkg/rtutorial/setter.go
  pkg/rtutorial/setter_test.go
  pkg/rtutorial/tutorial.go
  pkg/stream/mocks/mock.go
Labels: 2.0.0, feature

#312 Metadata
  pkg/api/api.go
  pkg/cmd/formulas.go
  pkg/formula/creator/creator.go
  pkg/formula/creator/modifier/formulaCmd.go
  pkg/formula/creator/modifier/formulaCmd_test.go
  pkg/formula/creator/modifier/formulaTags.go
  pkg/formula/creator/modifier/formulaTags_test.go
  pkg/formula/creator/modifier/modifier.go
  pkg/formula/creator/modifier/modifier_test.go
  pkg/formula/creator/template/default.go
  pkg/formula/formula.go
  pkg/formula/tree/generator.go
Labels: 2.0.0, feature

#302 Feature/build formula
  cmd/main.go
  go.mod
  pkg/cmd/add_repo.go
  pkg/cmd/build_formula.go
  pkg/cmd/create_formula.go
  pkg/cmd/delete_context.go
  pkg/cmd/delete_repo.go
  pkg/cmd/formula_test.go
  pkg/cmd/formulas.go
  pkg/cmd/init.go
  pkg/cmd/list_repo_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/root.go
  pkg/cmd/set_context.go
  pkg/cmd/set_credential.go
  pkg/cmd/tutorial.go
  pkg/cmd/update_repo.go
  pkg/file/fileutil/file_util.go
  pkg/formula/builder/bat.go
  pkg/formula/builder/build_test.go
  pkg/formula/builder/docker.go
  pkg/formula/builder/local.go
  pkg/formula/builder/make.go
  pkg/formula/create_builder.go
  pkg/formula/formula.go
  pkg/formula/runner/default_pre_runner.go
  pkg/formula/runner/default_runner.go
  pkg/formula/runner/default_runner_test.go
  pkg/formula/runner/default_setup.go
  pkg/formula/runner/docker_pre_runner.go
  pkg/formula/runner/docker_runner.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
  pkg/formula/runner/post_run.go
  pkg/formula/runner/pre_run.go
  pkg/formula/runner/pre_run_test.go
  pkg/formula/runner/runner.go
  pkg/formula/runner/runner_test.go
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
  pkg/stdin/stdin.go
  pkg/stream/file.go
  pkg/stream/streams/stream.go
  vendor/github.com/kaduartur/go-cli-spinner/pkg/spinner/spinner.go
  vendor/modules.txt
Labels: 2.0.0, WIP, feature

#311 Updated help messages
  functional/core/core_feature.json
  pkg/cmd/add.go
  pkg/cmd/add_repo.go
  pkg/cmd/autocomplete.go
  pkg/cmd/build.go
  pkg/cmd/create.go
  pkg/cmd/delete.go
  pkg/cmd/delete_context.go
  pkg/cmd/init.go
  pkg/cmd/list.go
  pkg/cmd/set.go
  pkg/cmd/show.go
  pkg/cmd/update.go
Labels: 2.0.0, WIP, improvement

#295 List credentials command
  cmd/main.go
  pkg/cmd/list.go
  pkg/cmd/list_credential.go
  pkg/cmd/list_credential_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/cmd/tutorial.go
  pkg/credential/credential.go
  pkg/credential/credsingle/credsingle_test.go
  pkg/credential/credsingle/setter_test.go
  pkg/credential/credsingle/settings.go
  pkg/credential/credsingle/settings_test.go
  pkg/credential/finder.go
  pkg/credential/finder_test.go
  pkg/credential/path.go
  pkg/credential/setter.go
  pkg/credential/setter_test.go
  pkg/credential/settings.go
  pkg/credential/settings_test.go
  pkg/crypto/cryptoutil/crypto_util.go
  pkg/crypto/cryptoutil/crypto_util_test.go
  pkg/prompt/color.go
  pkg/rcontext/finder.go
  pkg/rcontext/finder_test.go
  pkg/rcontext/remover_test.go
  pkg/rcontext/setter_test.go
  pkg/rtutorial/finder_test.go
  pkg/stream/file.go
  run-tests.sh
  testdata/.rit/credentials/default/jenkins
Labels: 2.0.0, WIP, feature

#317 Fix/build_docker
  pkg/formula/builder/build_test.go
  pkg/formula/builder/docker.go
  pkg/formula/builder/local.go
  pkg/formula/formula_test.go
  pkg/formula/runner/pre_run_test.go
  pkg/formula/runner/runner.go
  pkg/formula/runner/runner_test.go
  pkg/formula/watcher/watcher_test.go
  testdata/ritchie-formulas-test.zip
Labels: Windows, bug

#321 Change Set credencial
  cmd/main.go
  pkg/credential/finder.go
  pkg/credential/finder_test.go
  pkg/credential/settings.go
Labels: 2.0.0, WIP, improvement

#318 Improvement readme
  CONTRIBUTORS
  README.md
Labels: documentation, improvement

#323 Fix/list credential
  pkg/credential/settings.go
Labels: 2.0.0, improvement

#322 Verify Credencial of config.json
  pkg/credential/finder.go
  pkg/env/envcredential/env_credential.go
Labels: 2.0.0, improvement

#331 Change VerifyNewVersion
  pkg/version/version.go
Labels: 2.0.0, improvement

#333 [FEATURE] Path for win bin download
  .circleci/config.yml
  .circleci/scripts/gen-win.ps1
  Makefile
  README.md
  packaging/windows/ico.ico
  packaging/windows/ritchie-wix-templates/LicenseAgreementDlg_HK.wxs
  packaging/windows/ritchie-wix-templates/WixUI_HK.wxs
  packaging/windows/ritchie-wix-templates/product.wxs
  packaging/windows/wix.json
Labels: 2.0.0, Windows

#332 Change build formulas behavior
  cmd/main.go
  pkg/cmd/build_formula.go
  pkg/cmd/create_formula.go
  pkg/cmd/formula_test.go
  pkg/cmd/formulas.go
  pkg/credential/settings_test.go
  pkg/formula/builder/bat.go
  pkg/formula/builder/docker.go
  pkg/formula/builder/local.go
  pkg/formula/formula.go
  pkg/formula/runner/post_run.go
  pkg/formula/runner/pre_run.go
  pkg/formula/runner/pre_run_test.go
  pkg/formula/runner/runner.go
  pkg/formula/runner/runner_test.go
  pkg/formula/workspace.go
  run-tests.sh
Labels: 2.0.0, WIP, Windows, improvement

#335 change errKeyNotFoundTemplate
  pkg/env/envcredential/env_credential.go
Labels: 2.0.0, improvement

#330 Verbose flag
  pkg/cmd/formulas.go
  pkg/cmd/mocks_test.go
  pkg/credential/settings_test.go
  pkg/formula/formula.go
  pkg/formula/runner/post_run.go
  pkg/formula/runner/pre_run_test.go
  pkg/formula/runner/runner.go
  pkg/formula/runner/runner_test.go
Labels: 2.0.0, feature

#336 Fix work space that have space
  pkg/cmd/create_formula.go
  pkg/cmd/root.go
Labels: 2.0.0, bug

#338 [Fix] build local
  cmd/main.go
  pkg/formula/builder/bat.go
  pkg/formula/builder/local.go
  pkg/formula/formula.go
  pkg/formula/runner/runner.go
  pkg/formula/runner/runner_test.go
Labels: 2.0.0, bug

#337 List repo url
  pkg/cmd/list_repo.go
Labels: 2.0.0, improvement
