Repository ZupIT/ritchie-cli, pull requests merged in 2020-05, with the labels that each got.

#63 Feature/create formula any languages
  cmd/single/main.go
  cmd/team/main.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/formulas.go
  pkg/cmd/mocks_test.go
  pkg/formula/creator.go
  pkg/formula/creator_test.go
  pkg/formula/formula.go
  pkg/formula/runner.go
  pkg/formula/tpl/tpl_go/tpl_go.go
  pkg/formula/tpl/tpl_java/tpl_java.go
  pkg/formula/tpl/tpl_node/tpl_node.go
  pkg/formula/tpl/tpl_python/tpl_python.go
  pkg/formula/tpl/tpl_shell/tpl_shell.go
Labels: improvement

#65 Feature/group commands
  cmd/single/main.go
  cmd/team/main.go
  go.mod
  pkg/api/api.go
  pkg/cmd/formulas.go
  pkg/cmd/root.go
  pkg/formula/default_tree.go
Labels: feature, improvement, single, team

#66 Fix/create formula python
  cmd/single/main.go
  pkg/cmd/clean.go
  pkg/cmd/set_server_test.go
  pkg/cmd/show.go
  pkg/cmd/single.go
  pkg/file/fileutil/file_util.go
  pkg/formula/creator.go
  pkg/formula/default_repo.go
  pkg/formula/tpl/tpl_python/tpl_python.go
  pkg/server/server.go
  pkg/server/setter.go
  pkg/server/setter_test.go
Labels: bug

#71 [FIX] updating single repo commons url
  Makefile
Labels: bug, priority:high

#81 [FIX] updating gitbook urls
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  go.mod
Labels: bug, documentation

#79 [FEATURE] Add credential for the organizations
  pkg/cmd/set_credential.go
  pkg/credential/credential.go
  pkg/credential/credteam/setter.go
Labels: feature, team

#92 [MERGE] Fix Server Error PR into QA
  cmd/team/main.go
  pkg/cmd/set_server.go
  pkg/credential/credteam/credteam_test.go
  pkg/credential/credteam/finder_test.go
  pkg/credential/credteam/setter_test.go
  pkg/credential/credteam/settings_test.go
  pkg/server/finder_test.go
  pkg/server/setter.go
  pkg/server/setter_test.go
  pkg/validator/validator.go
Labels: QA

#90 Feature/dockerfile create f
  pkg/formula/creator.go
  pkg/formula/tpl/tpl_go/tpl_go.go
  pkg/formula/tpl/tpl_java/tpl_java.go
  pkg/formula/tpl/tpl_node/tpl_node.go
  pkg/formula/tpl/tpl_python/tpl_python.go
  pkg/formula/tpl/tpl_shell/tpl_shell.go
Labels: feature, improvement

#95 Feature/access control for formulas
  cmd/team/main.go
  go.mod
  pkg/cmd/formulas.go
  pkg/formula/default_repo.go
  pkg/formula/formula.go
  pkg/formula/runner.go
Labels: feature

#76 [FEATURE] Move the fileutil to stream package
  pkg/stream/dir.go
  pkg/stream/file.go
  pkg/stream/streams/stream.go
Labels: feature

#84 [FIX] Set server error
  cmd/team/main.go
  pkg/cmd/set_server.go
  pkg/credential/credteam/credteam_test.go
  pkg/credential/credteam/finder_test.go
  pkg/credential/credteam/setter_test.go
  pkg/credential/credteam/settings_test.go
  pkg/server/finder_test.go
  pkg/server/setter.go
  pkg/server/setter_test.go
  pkg/validator/validator.go
Labels: bug, improvement

#97 [FEATURE] STDIN Implementation
  cmd/single/main.go
  cmd/team/main.go
  functional/core_feature.json
  go.mod
  pkg/api/api.go
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/clean_repo.go
  pkg/cmd/clean_repo_test.go
  pkg/cmd/cmd.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/create_user.go
  pkg/cmd/create_user_test.go
  pkg/cmd/delete_context.go
  pkg/cmd/delete_context_test.go
  pkg/cmd/delete_repo.go
  pkg/cmd/delete_repo_test.go
  pkg/cmd/delete_user.go
  pkg/cmd/formulas.go
  pkg/cmd/root.go
  pkg/cmd/set_context.go
  pkg/cmd/set_context_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/cmd/set_server.go
  pkg/cmd/set_server_test.go
  pkg/cmd/update_repo_test.go
  pkg/formula/formula.go
  pkg/formula/runner.go
  pkg/stdin/stdin.go
  pkg/stdin/stdin_test.go
Labels: feature, improvement

#114 Improve Pipeline with security test
  .circleci/config.yml
Labels: security

#111 [FIX] bin name linux
  pkg/formula/formula.go
Labels: bug

#106 [FIX] changelog
  Makefile
  bucket.sh
  credentials.sh
  ritchie_env.sh
  ritchie_server.sh
  version.sh
Labels: improvement

#104 [FEATURE] Formula creator improvements
  cmd/single/main.go
  cmd/team/main.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/creator.go
  pkg/formula/creator_test.go
  pkg/formula/formula.go
  pkg/formula/lang.go
  pkg/formula/tpl/tpl_go/tpl_go.go
  pkg/formula/tpl/tpl_java/tpl_java.go
  pkg/formula/tpl/tpl_node/tpl_node.go
  pkg/formula/tpl/tpl_python/tpl_python.go
  pkg/formula/tpl/tpl_shell/tpl_shell.go
  testdata/Makefile
Labels: feature, improvement
