Repository ZupIT/ritchie-cli, pull requests merged in 2020-04, with the labels that each got.

#11 [Enhancement] Contributing file
  CONTRIBUTING.md
  README.md
  docs/img/git-branchs.png
Labels: enhancement

#14 feature/prompt_interface
  cmd/single/main.go
  cmd/team/main.go
  pkg/cmd/add_repo.go
  pkg/cmd/clean_repo.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_user.go
  pkg/cmd/delete_context.go
  pkg/cmd/delete_repo.go
  pkg/cmd/delete_user.go
  pkg/cmd/login.go
  pkg/cmd/root.go
  pkg/cmd/set_context.go
  pkg/cmd/set_credential.go
  pkg/formula/runner.go
  pkg/prompt/bool.go
  pkg/prompt/email.go
  pkg/prompt/int.go
  pkg/prompt/list.go
  pkg/prompt/password.go
  pkg/prompt/prompt.go
  pkg/prompt/text.go
  pkg/prompt/url.go
  pkg/rcontext/context.go
Labels: enhancement

#17 [Enhancement] Contributing file
  CONTRIBUTING.md
  README.md
Labels: enhancement

#21 Feature/improve_session_validator
  .editorconfig
  go.mod
  pkg/cmd/root.go
  pkg/session/sessteam/validator_team.go
  pkg/session/sessteam/validator_team_test.go
Labels: feature

#20 [FEATURE] updating issues contribution templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/OWNERS
  CODEOWNERS
Labels: feature

#29 Circleci project setup
  .circleci/config.yml
  Makefile
  README.md
  bucket.sh
  credentials.sh
  version.sh
Labels: feature

#36 Feature/lint
  .circleci/config.yml
Labels: feature, single, team

#41 Require lint
  pkg/cmd/clean.go
  pkg/cmd/show_context.go
  pkg/credential/credsingle/finder_test.go
  pkg/credential/credteam/credteam_test.go
  pkg/crypto/cryptoutil/crypto_util.go
  pkg/file/fileutil/file_util.go
  pkg/formula/creator.go
  pkg/formula/default_repo.go
  pkg/formula/runner.go
  pkg/metrics/metrics.go
  pkg/rcontext/finder_test.go
  pkg/rcontext/remover_test.go
  pkg/security/oauth/login.go
  pkg/security/oauth/logout.go
  pkg/security/oauth/oauth.go
  pkg/security/secteam/provider.go
  pkg/workspace/default_workspace.go
Labels: bug, single, team

#35 [FIX ] use $(HOME) instead of ~ in Makefile (main)
  pkg/formula/tpl/tplgo/tpl_go.go
Labels: feature

#34 [FEATURE] Creation set server cmd (TEAM)
  Makefile
  cmd/single/main.go
  cmd/team/main.go
  pkg/cmd/root.go
  pkg/cmd/set_server.go
  pkg/cmd/set_server_test.go
  pkg/credential/credteam/finder.go
  pkg/credential/credteam/finder_test.go
  pkg/credential/credteam/setter.go
  pkg/credential/credteam/setter_test.go
  pkg/credential/credteam/settings.go
  pkg/credential/credteam/settings_test.go
  pkg/formula/default_repo.go
  pkg/metrics/metrics.go
  pkg/security/secteam/login.go
  pkg/security/secteam/logout.go
  pkg/security/secteam/user.go
  pkg/server/finder.go
  pkg/server/finder_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/setter.go
  pkg/server/setter_test.go
  pkg/server/validator.go
  pkg/server/validator_test.go
  pkg/validator/validator.go
Labels: feature, team

#52 adding stale bot to ritchie-cli
  .github/stale.yml
Labels: feature

#48 Feature/any languages
  go.mod
  pkg/api/api.go
  pkg/cmd/formulas.go
  pkg/file/fileutil/file_util.go
  pkg/formula/creator.go
  pkg/formula/formula.go
  pkg/formula/runner.go
  pkg/formula/tpl/tplgo/tpl_go.go
Labels: feature

#53 Feature/code of conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, feature

#62 [FEATURE] Set server cmd update
  pkg/security/secteam/login.go
  pkg/server/finder_test.go
  pkg/server/setter.go
  pkg/server/setter_test.go
Labels: feature

#61 Feature/add bin other so tree
  pkg/api/api.go
  pkg/cmd/formulas.go
  pkg/formula/formula.go
Labels: feature
