Repository ZupIT/ritchie-cli, pull requests merged in 2020-09, with the labels that each got.

#456 upgrade when version server don't respond with 200
  cmd/main.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/list_credential.go
  pkg/cmd/list_credential_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/root.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/cmd/upgrade.go
  pkg/cmd/upgrade_test.go
  pkg/file/fileextensions/extensions.go
  pkg/file/fileutil/file_util.go
  pkg/metric/checker_test.go
  pkg/stream/mocks/mock.go
  pkg/upgrade/manager.go
  pkg/upgrade/manager_test.go
  pkg/upgrade/updater.go
  pkg/upgrade/url_finder.go
  pkg/upgrade/url_finder_test.go
  pkg/version/resolver.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#493 Add stdin validation for docker execution
  pkg/formula/runner/docker/runner.go
Labels: :beetle: bug

#487 add metrics question on rit upgrade command
  cmd/main.go
  functional/core/core_feature.json
  functional/init/init_feature.json
  pkg/api/api.go
  pkg/cmd/upgrade.go
  pkg/cmd/upgrade_test.go
  pkg/metric/checker.go
Labels: :heavy_check_mark: ready-for-review, :rocket: QA

#503 Improved CI to avoid 'killed signal' error
  .circleci/config.yml
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#496 Remove command lock without initialization
  Makefile
  functional/core/core_integration_test.go
  functional/init/init_feature.json
  functional/init/init_integration_test.go
  functional/scaffold/scaffold_integration_test.go
  functional/stdin/stdin_integration_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/root.go
  pkg/cmd/root_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#506 show docker logs on formula build
  pkg/formula/runner/docker/pre_run.go
Labels: :hammer: improvement, :rocket: QA

#514 update lint executor
  .circleci/config.yml
Labels: :beetle: bug

#509 Added changes suggested by goimports
  pkg/cmd/add_repo_test.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/set_context.go
  pkg/cmd/set_formula_runner_test.go
  pkg/cmd/upgrade.go
  pkg/credential/credential.go
  pkg/env/envcredential/env_credential_test.go
  pkg/file/fileutil/file_util.go
  pkg/formula/builder/bat.go
  pkg/formula/formula.go
  pkg/formula/formula_test.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
  pkg/git/git.go
  pkg/metric/checker.go
  pkg/metric/checker_test.go
  pkg/metric/user_id_generator.go
  pkg/prompt/color.go
  pkg/prompt/int.go
  pkg/prompt/multiline.go
  pkg/prompt/text.go
  pkg/rcontext/context_test.go
  pkg/rcontext/finder_test.go
  pkg/rcontext/remover.go
  pkg/stdin/stdin_test.go
  pkg/stream/mocks/mock.go
  pkg/upgrade/url_finder.go
  pkg/version/resolver.go
Labels: :hammer: improvement, :rocket: QA

#519 change executor to a ubuntu machine
  .circleci/config.yml
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#505 Fixed privileges for the msi installer to use the program files folder.
  packaging/windows/ritchie-wix-templates/product.wxs
Labels: :beetle: bug, :rocket: QA, Windows

#515 Added tests to update repo command
  pkg/cmd/mocks_test.go
  pkg/cmd/update_repo.go
  pkg/cmd/update_repo_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#517 Added commons repository acceptance info to metrics
  pkg/cmd/init.go
  pkg/metric/data_collector.go
  pkg/metric/metric.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#499 add check for http status
  .circleci/config.yml
  pkg/version/version.go
  pkg/version/version_test.go
Labels: 1.0.0, :beetle: bug, :heavy_check_mark: ready-for-review

#523 Command's run time
  cmd/main.go
  pkg/metric/data_collector.go
  pkg/metric/data_collector_test.go
  pkg/metric/metric.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#518 Add column from latest version on list repo command
  cmd/main.go
  pkg/cmd/list_repo.go
  pkg/cmd/list_repo_test.go
  pkg/cmd/mocks_test.go
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#530 Displays error when invalid argument added to command
  functional/core/core_feature.json
  pkg/cmd/add.go
  pkg/cmd/add_repo.go
  pkg/cmd/autocomplete.go
  pkg/cmd/build.go
  pkg/cmd/build_formula.go
  pkg/cmd/create.go
  pkg/cmd/create_formula.go
  pkg/cmd/delete.go
  pkg/cmd/delete_context.go
  pkg/cmd/delete_formula.go
  pkg/cmd/delete_repo.go
  pkg/cmd/init.go
  pkg/cmd/list.go
  pkg/cmd/list_credential.go
  pkg/cmd/list_repo.go
  pkg/cmd/metrics.go
  pkg/cmd/root.go
  pkg/cmd/set.go
  pkg/cmd/set_context.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_formula_runner.go
  pkg/cmd/set_priority.go
  pkg/cmd/show.go
  pkg/cmd/show_context.go
  pkg/cmd/show_formula_runner.go
  pkg/cmd/tutorial.go
  pkg/cmd/update.go
  pkg/cmd/update_repo.go
  pkg/cmd/upgrade.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#527 Fixing conditional bug
  pkg/formula/runner/inputs.go
Labels: :beetle: bug, :hammer: improvement

#532 add repo info to metrics
  cmd/main.go
  pkg/api/api.go
  pkg/formula/runner/docker/pre_run.go
  pkg/formula/runner/local/runner.go
  pkg/metric/data_collector.go
  pkg/metric/data_collector_test.go
  pkg/metric/metric.go
  pkg/stream/mocks/mock.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#534 Add support to the tutorial field in config.json
  pkg/cmd/mocks_test.go
  pkg/env/envcredential/env_credential_test.go
  pkg/formula/formula.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
  pkg/formula/runner/local/runner_test.go
  pkg/prompt/bool.go
  pkg/prompt/list.go
  pkg/prompt/password.go
  pkg/prompt/prompt.go
Labels: :rocket: QA, :sparkles: feature

#481 Delete workspace command
  cmd/main.go
  functional/core/core_feature.json
  pkg/api/api.go
  pkg/cmd/delete.go
  pkg/cmd/delete_workspace.go
  pkg/cmd/delete_workspace_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/workspace.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#538 Preparing for the Hacktoberfest
  CONTRIBUTING.md
  README.md
Labels: :books: documentation, Hacktoberfest

#540 Remove the ritchie path from the metricId
  pkg/metric/data_collector.go
Labels: :beetle: bug, :rocket: QA, Windows, priority:high

#539 Upgrade metric api
  .circleci/config.yml
  .circleci/scripts/credentials.sh
  .circleci/scripts/ritchie_metric_server.sh
  Makefile
  pkg/metric/http_sender.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#537 add metrics acceptance question info
  cmd/main.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/metric/metric.go
Labels: :hammer: improvement

#547 Hotfix/readme command
  README.md
  pkg/cmd/root.go
Labels: :beetle: bug, :books: documentation, :heavy_check_mark: ready-for-review

#551 Add required field to Input struct
  pkg/formula/formula.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
Labels: :rocket: QA, :sparkles: feature

#548 Add defer to PostRun function
  pkg/formula/runner/docker/runner.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/local/runner.go
  pkg/formula/runner/post_run.go
Labels: :beetle: bug, :rocket: QA

#552 Wizard - Use formulas
  pkg/cmd/init.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#562 Update horus cmd
  .circleci/config.yml
Labels: :beetle: bug

#563 Add sending metrics for the --watch flag
  cmd/main.go
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
Labels: :beetle: bug, :rocket: QA

#561 Added tests to default tree file
  pkg/formula/tree/default_tree_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#567 Use version 1.3.0 of horus
  .circleci/config.yml
  pkg/cmd/create_formula_test.go
Labels: :heavy_check_mark: ready-for-review, priority:high
