Repository ZupIT/ritchie-cli, pull requests merged in 2020-10, with the labels that each got.

#569 Add info build formula
  pkg/cmd/build_formula.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, usability

#544 add check for core commands on create formula
  functional/core/core_integration_test.go
  functional/stdin/stdin_feature.json
  functional/stdin/stdin_integration_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/runner/docker/runner.go
Labels: :heavy_check_mark: ready-for-review

#568 Default tree refactoring to use file manager of package stream
  cmd/main.go
  pkg/autocomplete/generator_test.go
  pkg/formula/creator/creator_test.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#586 Remove preinst.sh script
  packaging/debian/deb.json
  packaging/rpm/rpm.json
  packaging/scripts/postinst.sh
  packaging/scripts/preinst.sh
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#583 Set tutorial output more informative
  functional/core/core_feature.json
  pkg/cmd/tutorial.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, Hacktoberfest

#512 Add validation with regex in the config.json inputs
  cmd/main.go
  pkg/formula/formula.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
  pkg/formula/runner/local/runner_test.go
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#596 refactor: add timeout to the functional testing job
  .circleci/config.yml
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#595 stable version was not updating when generate release
  Makefile
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#582 Added new version warning for repositories in rit helper
  cmd/main.go
  pkg/autocomplete/generator_test.go
  pkg/formula/creator/creator_test.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
Labels: :hammer: improvement, :rocket: QA

#593 Update README file
  README.md
  docs/img/formulas-explanation.png
Labels: :books: documentation, :heavy_check_mark: ready-for-review

#610 [Fix] - Lower case containerId string
  pkg/formula/runner/docker/pre_run.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#601 Fix timer os metric build formula watch
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#604 Adding developer guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTORS
  DEVELOPER_GUIDE.md
  README.md
  docs/img/go-land-setup.png
Labels: :books: documentation, :heavy_check_mark: ready-for-review

#485 List workspace command
  cmd/main.go
  pkg/api/api.go
  pkg/cmd/build_formula.go
  pkg/cmd/build_formula_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/delete_formula.go
  pkg/cmd/delete_formula_test.go
  pkg/cmd/list.go
  pkg/cmd/list_workspace.go
  pkg/cmd/list_workspace_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/workspace.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#599 Add env docker_execution
  pkg/formula/formula.go
  pkg/formula/runner/docker/runner.go
  pkg/formula/runner/local/runner.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#605 Feature/dynamic list
  go.mod
  pkg/formula/formula.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
  vendor/github.com/PaesslerAG/gval/.gitignore
  vendor/github.com/PaesslerAG/gval/.travis.yml
  vendor/github.com/PaesslerAG/gval/LICENSE
  vendor/github.com/PaesslerAG/gval/README.md
  vendor/github.com/PaesslerAG/gval/evaluable.go
  vendor/github.com/PaesslerAG/gval/functions.go
  vendor/github.com/PaesslerAG/gval/go.mod
  vendor/github.com/PaesslerAG/gval/go.sum
  vendor/github.com/PaesslerAG/gval/gval.go
  vendor/github.com/PaesslerAG/gval/language.go
  vendor/github.com/PaesslerAG/gval/operator.go
  vendor/github.com/PaesslerAG/gval/parse.go
  vendor/github.com/PaesslerAG/gval/parser.go
  vendor/github.com/PaesslerAG/gval/prtg-batmin-gopher.png
  vendor/github.com/PaesslerAG/jsonpath/.gitignore
  vendor/github.com/PaesslerAG/jsonpath/.travis.yml
  vendor/github.com/PaesslerAG/jsonpath/LICENSE
  vendor/github.com/PaesslerAG/jsonpath/README.md
  vendor/github.com/PaesslerAG/jsonpath/go.mod
  vendor/github.com/PaesslerAG/jsonpath/go.sum
  vendor/github.com/PaesslerAG/jsonpath/jsonpath.go
  vendor/github.com/PaesslerAG/jsonpath/parse.go
  vendor/github.com/PaesslerAG/jsonpath/path.go
  vendor/github.com/PaesslerAG/jsonpath/placeholder.go
  vendor/github.com/PaesslerAG/jsonpath/selector.go
  vendor/github.com/PaesslerAG/jsonpath/test.sh
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#598 [Fix] - Searching only for run.sh on docker pre run
  pkg/formula/formula.go
  pkg/formula/runner/docker/pre_run.go
Labels: :beetle: bug, :rocket: QA, Windows

#629 Remove codecov/project step
  codecov.yml
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#614 Improvement pipeline
  .circleci/config.yml
  .circleci/scripts/bucket.sh
  .circleci/scripts/credentials.sh
  .circleci/scripts/gonna_release.sh
  .circleci/scripts/next_version.sh
  .circleci/scripts/ritchie_env.sh
  .circleci/scripts/ritchie_metric_server.sh
  .circleci/scripts/ritchie_server.sh
  .circleci/scripts/routing.sh
  .circleci/scripts/version.sh
  Makefile
Labels: :clock3: Wait, :heavy_check_mark: ready-for-review, :sparkles: feature

#632 added context printing
  pkg/formula/runner/local/pre_run.go
  pkg/formula/runner/local/runner.go
  pkg/formula/runner/local/runner_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#578 Prompt to auto rebuild formula on source modifications
  CONTRIBUTORS
  cmd/main.go
  go.mod
  pkg/cmd/build_formula.go
  pkg/cmd/build_formula_test.go
  pkg/cmd/mocks_test.go
  pkg/formula/runner.go
  pkg/formula/runner/executor.go
  pkg/formula/runner/executor_test.go
  pkg/formula/runner/pre_run_builder.go
  pkg/formula/runner/pre_run_builder_test.go
  pkg/formula/workspace.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
  pkg/stream/dir.go
  pkg/stream/file.go
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/mod/PATENTS
  vendor/golang.org/x/mod/sumdb/dirhash/hash.go
  vendor/modules.txt
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, Hacktoberfest, hacktoberfest-accepted, usability

#633 added warning on same env name
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#640 Improvement/build_interface
  pkg/commands/builder.go
  pkg/formula/builder/bat.go
  pkg/formula/builder/docker.go
  pkg/formula/builder/docker_test.go
  pkg/formula/builder/make.go
  pkg/formula/builder/make_test.go
  pkg/formula/builder/shell.go
  pkg/formula/builder/shell_test.go
  pkg/formula/formula.go
  pkg/formula/runner/docker/pre_run.go
  pkg/formula/runner/docker/pre_run_test.go
  pkg/formula/runner/local/pre_run.go
  pkg/formula/runner/local/pre_run_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#644 JS Lint
  testdata/repos/commons/templates/create_formula/languages/node/src/hello/hello.js
Labels: :beetle: bug, :hammer: improvement, :heavy_check_mark: ready-for-review
