Repository ZupIT/ritchie-cli, pull requests merged in 2020-12, with the labels that each got.

#707 Fix/readme add demo repo
  README.md
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review

#725 disable add issues to projects with ritchie-bot
  .github/ritchie-bot-config.yml
Labels: :heavy_check_mark: ready-for-review

#678 Change metric structs
  cmd/main.go
  internal/mocks/mocks.go
  pkg/cmd/add_repo.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/list_repo.go
  pkg/cmd/list_repo_test.go
  pkg/cmd/update_repo.go
  pkg/cmd/update_repo_test.go
  pkg/commands/builder.go
  pkg/formula/builder/local.go
  pkg/formula/repo.go
  pkg/formula/repo/adder_test.go
  pkg/formula/repo/creator.go
  pkg/formula/repo/creator_test.go
  pkg/formula/repo/deleter_test.go
  pkg/formula/repo/detail.go
  pkg/formula/repo/detail_test.go
  pkg/formula/repo/lister_test.go
  pkg/formula/tree/default_tree_test.go
  pkg/metric/checker_test.go
  pkg/metric/data_collector.go
  pkg/metric/data_collector_test.go
  pkg/metric/grpc_sender.go
  pkg/metric/grpc_sender_test.go
  pkg/metric/http_sender.go
  pkg/metric/http_sender_test.go
  pkg/metric/metric.go
  pkg/metric/user_id_generator.go
  pkg/metric/user_id_generator_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#709 Deprecating stdin
  functional/runner.go
  pkg/cmd/cmd.go
  pkg/formula/runner/input_resolver.go
Labels: :rocket: QA

#705 Check repository structure
  pkg/cmd/add_repo_test.go
  pkg/cmd/mocks_test.go
  pkg/commands/builder.go
  pkg/formula/builder/local_test.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/adder_test.go
  pkg/formula/repo/list_adder_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#772 Fixing codecov patch at 80%
  codecov.yml
Labels: :heavy_check_mark: ready-for-review

#771 Feature/release notes on cli
  internal/mocks/mocks.go
  pkg/cmd/upgrade.go
  pkg/cmd/upgrade_test.go
  pkg/commands/builder.go
  pkg/git/git.go
  pkg/git/github/github.go
  pkg/git/github/repository.go
  pkg/git/github/repository_test.go
  pkg/git/gitlab/repository.go
  pkg/git/gitlab/repository_test.go
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#777 Fix/struct solution
  pkg/git/git.go
  pkg/git/gitlab/repository.go
  pkg/git/gitlab/repository_test.go
Labels: :beetle: bug

#704 Add step to verify repo existence
  internal/mocks/mocks.go
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/upgrade_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#769 feat: add multiselect input
  pkg/commands/builder.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/local/runner_test.go
  pkg/prompt/multiselect.go
  pkg/prompt/prompt.go
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :sparkles: feature

#803 New horus pipeline
  .circleci/config.yml
Labels: chore

#768 Performance new tree struct
  go.mod
  internal/mocks/mocks.go
  pkg/api/api.go
  pkg/autocomplete/generator.go
  pkg/autocomplete/generator_test.go
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/formula.go
  pkg/cmd/formula_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/root.go
  pkg/cmd/root_test.go
  pkg/commands/builder.go
  pkg/formula/creator/creator_test.go
  pkg/formula/repo.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/adder_test.go
  pkg/formula/tree.go
  pkg/formula/tree/checker.go
  pkg/formula/tree/checker_test.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
  pkg/formula/tree/generator.go
  pkg/formula/tree/generator_test.go
  pkg/slice/sliceutil/slice_util.go
  vendor/modules.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :racehorse: Performance, :rocket: QA

#805 Improve performance to "rit create formula" command
  functional/stdin/stdin_feature.json
  internal/mocks/mocks.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :racehorse: Performance, :rocket: QA

#806 Tests on credential pkg
  pkg/commands/builder.go
  pkg/credential/credential.go
  pkg/credential/delete.go
  pkg/credential/delete_test.go
  pkg/credential/finder.go
  pkg/credential/finder_test.go
  pkg/credential/path.go
  pkg/credential/resolver_test.go
  pkg/credential/setter.go
  pkg/credential/setter_test.go
  pkg/credential/settings_test.go
Labels: :broom: chore, :heavy_check_mark: ready-for-review

#808 Tests on slice
  pkg/cmd/delete_formula.go
  pkg/cmd/formula.go
  pkg/cmd/formula_test.go
  pkg/slice/sliceutil/slice_util.go
  pkg/slice/sliceutil/slice_util_test.go
Labels: :broom: chore, :heavy_check_mark: ready-for-review, :rocket: QA

#809 created rit add workspace command
  internal/mocks/mocks.go
  pkg/api/api.go
  pkg/cmd/add_workspace.go
  pkg/cmd/add_workspace_test.go
  pkg/commands/builder.go
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#815 Fix add empty local repo
  pkg/formula/repo/adder.go
  pkg/formula/repo/adder_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review
