Repository ZupIT/ritchie-cli, pull requests merged in 2020-11, with the labels that each got.

#651 Change apk add from python to python3.
  Dockerfile
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#656 Remove repository version check
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
Labels: :heavy_check_mark: ready-for-review, priority:high, usability

#638 warning when formulas commands conflicts
  cmd/main.go
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/mocks_test.go
  pkg/commands/builder.go
  pkg/formula/tree.go
  pkg/formula/tree/checker.go
  pkg/formula/tree/checker_test.go
  pkg/formula/tree/default_tree.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#602 Added update All for repo
  CONTRIBUTORS
  pkg/cmd/update_repo.go
  pkg/cmd/update_repo_test.go
Labels: :hammer: improvement, :rocket: QA, Hacktoberfest

#635 add default flag
  pkg/cmd/formula.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
Labels: :heavy_check_mark: ready-for-review

#654 feat: add default text input to formula
  pkg/commands/builder.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
  pkg/formula/input/prompt/text_default.go
  pkg/formula/input/prompt/text_default_test.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/local/runner_test.go
Labels: :hammer: improvement, :rocket: QA, usability

#672 fix: fix lint
  pkg/cmd/update_repo.go
  pkg/formula/input/prompt/prompt_test.go
Labels: :hammer: improvement

#666 Feature/split_local
  pkg/cmd/build_formula.go
  pkg/cmd/create_formula.go
  pkg/cmd/list_repo.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_priority.go
  pkg/cmd/update_repo.go
  pkg/commands/builder.go
  pkg/formula/builder/local.go
  pkg/formula/builder/local_test.go
  pkg/formula/formula.go
  pkg/formula/repo.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/adder_test.go
  pkg/formula/repo/deleter.go
  pkg/formula/repo/deleter_test.go
  pkg/formula/repo/list_adder_test.go
  pkg/formula/repo/list_updater_test.go
  pkg/formula/repo/list_write_creator.go
  pkg/formula/repo/list_write_creator_test.go
  pkg/formula/repo/list_writer.go
  pkg/formula/repo/lister.go
  pkg/formula/repo/priority_setter.go
  pkg/formula/repo/priority_setter_test.go
  pkg/formula/repo/updater.go
  pkg/formula/repo/updater_test.go
  pkg/formula/repo/writer.go
  pkg/formula/repo/writer_test.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#675 split local repository by workspace
  pkg/cmd/build_formula.go
  pkg/cmd/build_formula_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/list_repo.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_priority.go
  pkg/cmd/update_repo.go
  pkg/commands/builder.go
  pkg/formula/builder/bat.go
  pkg/formula/builder/docker.go
  pkg/formula/builder/docker_test.go
  pkg/formula/builder/local.go
  pkg/formula/builder/local_test.go
  pkg/formula/builder/make.go
  pkg/formula/builder/make_test.go
  pkg/formula/builder/shell.go
  pkg/formula/builder/shell_test.go
  pkg/formula/create_builder.go
  pkg/formula/creator/creator.go
  pkg/formula/creator/creator_test.go
  pkg/formula/formula.go
  pkg/formula/repo.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/adder_test.go
  pkg/formula/repo/deleter.go
  pkg/formula/repo/deleter_test.go
  pkg/formula/repo/list_adder_test.go
  pkg/formula/repo/list_updater_test.go
  pkg/formula/repo/list_write_creator.go
  pkg/formula/repo/list_write_creator_test.go
  pkg/formula/repo/list_writer.go
  pkg/formula/repo/lister.go
  pkg/formula/repo/priority_setter.go
  pkg/formula/repo/priority_setter_test.go
  pkg/formula/repo/updater.go
  pkg/formula/repo/updater_test.go
  pkg/formula/repo/writer.go
  pkg/formula/repo/writer_test.go
  pkg/formula/runner/docker/pre_run.go
  pkg/formula/runner/docker/pre_run_test.go
  pkg/formula/runner/local/pre_run.go
  pkg/formula/runner/local/pre_run_test.go
  pkg/formula/runner/pre_run_builder.go
  pkg/formula/runner/pre_run_builder_test.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#681 Remove env pkg and move Resolver credential to credential pkg
  pkg/commands/builder.go
  pkg/credential/credential.go
  pkg/credential/resolver.go
  pkg/credential/resolver_test.go
  pkg/env/env.go
  pkg/env/envcredential/env_credential_test.go
  pkg/formula/input/flag/flag.go
  pkg/formula/input/flag/flag_test.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
  pkg/formula/input/stdin/stdin.go
  pkg/formula/input/stdin/stdin_test.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/local/runner_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#687 Move rcontext to env package
  pkg/cmd/delete_context.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_context.go
  pkg/cmd/show_context.go
  pkg/commands/builder.go
  pkg/credential/finder.go
  pkg/credential/finder_test.go
  pkg/credential/resolver_test.go
  pkg/credential/setter.go
  pkg/credential/setter_test.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/find_remover.go
  pkg/env/find_setter.go
  pkg/env/finder.go
  pkg/env/finder_test.go
  pkg/env/remover.go
  pkg/env/remover_test.go
  pkg/env/setter.go
  pkg/env/setter_test.go
  pkg/formula/runner/docker/runner.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/local/runner.go
  pkg/formula/runner/local/runner_test.go
  pkg/formula/workspace/workspace_test.go
  pkg/rcontext/remover.go
  pkg/rcontext/setter.go
  pkg/rcontext/setter_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#690 update horus url
  .circleci/config.yml
Labels: :heavy_check_mark: ready-for-review

#688 Create new command rit set env
  functional/core/core_feature.json
  functional/init/init_feature.json
  functional/init/init_integration_test.go
  functional/stdin/stdin_feature.json
  pkg/api/api.go
  pkg/cmd/cmd.go
  pkg/cmd/delete_context.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set.go
  pkg/cmd/set_env.go
  pkg/cmd/set_env_test.go
  pkg/cmd/show_context.go
  pkg/commands/builder.go
  pkg/credential/finder.go
  pkg/credential/setter.go
  pkg/env/env.go
  pkg/env/remover.go
  pkg/env/remover_test.go
  pkg/env/setter.go
  pkg/env/setter_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#691 Create new rit show env command
  functional/core/core_feature.json
  functional/init/init_feature.json
  functional/init/init_integration_test.go
  pkg/api/api.go
  pkg/cmd/mocks_test.go
  pkg/cmd/show.go
  pkg/cmd/show_env.go
  pkg/cmd/show_env_test.go
  pkg/commands/builder.go
  pkg/credential/finder.go
  pkg/credential/finder_test.go
  pkg/credential/path.go
  pkg/credential/resolver_test.go
  pkg/credential/setter.go
  pkg/credential/setter_test.go
  pkg/formula/runner/docker/runner.go
  pkg/formula/runner/local/runner.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#694 Create new rit delete env command
  functional/core/core_feature.json
  functional/init/init_feature.json
  functional/init/init_integration_test.go
  functional/stdin/stdin_feature.json
  pkg/api/api.go
  pkg/cmd/delete.go
  pkg/cmd/delete_env.go
  pkg/cmd/delete_env_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/show_env.go
  pkg/commands/builder.go
  pkg/formula/runner/local/runner.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#655 Feature/delete credential
  functional/core/core_feature.json
  pkg/api/api.go
  pkg/cmd/delete.go
  pkg/cmd/delete_credential.go
  pkg/cmd/delete_credential_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/update_repo_test.go
  pkg/commands/builder.go
  pkg/credential/credential.go
  pkg/credential/delete.go
  pkg/credential/delete_test.go
  pkg/credential/settings.go
  pkg/credential/settings_test.go
  testdata/.rit/credentialserr/error/github
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :sparkles: feature

#693 fix: add check for variables with the same name
  pkg/cmd/formula.go
  pkg/cmd/formula_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#689 Command based text to help.json
  pkg/formula/creator/creator.go
  pkg/formula/creator/creator_test.go
  pkg/formula/creator/template/default.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#692 Kill bill(d)
  .golangci.yml
  go.mod
  pkg/cmd/build_formula.go
  pkg/cmd/build_formula_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/delete_formula.go
  pkg/cmd/delete_formula_test.go
  pkg/cmd/mocks_test.go
  pkg/commands/builder.go
  pkg/formula/builder/local.go
  pkg/formula/formula.go
  pkg/formula/input/prompt/text_default_test.go
  pkg/formula/runner/executor.go
  pkg/formula/runner/pre_run_builder.go
  pkg/formula/runner/pre_run_builder_test.go
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
  vendor/github.com/radovskyb/watcher/.travis.yml
  vendor/github.com/radovskyb/watcher/LICENSE
  vendor/github.com/radovskyb/watcher/README.md
  vendor/github.com/radovskyb/watcher/ishidden.go
  vendor/github.com/radovskyb/watcher/ishidden_windows.go
  vendor/github.com/radovskyb/watcher/samefile.go
  vendor/github.com/radovskyb/watcher/samefile_windows.go
  vendor/github.com/radovskyb/watcher/watcher.go
  vendor/modules.txt
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review

#700 Fix update repo when all option selected
  pkg/cmd/update_repo.go
  pkg/cmd/update_repo_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA
