Repository ZupIT/ritchie-cli, pull requests merged in 2020-08, with the labels that each got.

#344 [FEATURE] Beautification for windows
  pkg/cmd/build_formula.go
  pkg/cmd/create_formula.go
  pkg/cmd/list_credential.go
  pkg/cmd/root.go
  pkg/formula/creator/creator.go
  pkg/formula/creator/template/manager.go
  pkg/formula/formula.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/creator.go
  pkg/formula/repo/deleter.go
  pkg/formula/repo/lister.go
  pkg/formula/repo/priority_setter.go
  pkg/formula/repo/updater.go
  pkg/formula/runner/runner.go
  pkg/formula/tree/generator.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: 2.0.0, Windows, improvement

#348 [FIX] Fix make build stderr
  pkg/formula/builder/bat.go
  pkg/formula/builder/docker_test.go
  pkg/formula/builder/local_test.go
  pkg/formula/builder/make.go
  pkg/formula/builder/make_test.go
Labels: 2.0.0, Linux, bug

#346 Fix linter
  .circleci/config.yml
Labels: bug

#327 Adding ansible credentials and bugfix for 2.0
  pkg/credential/settings.go
  pkg/credential/settings_test.go
  testdata/credentials.json
Labels: 2.0.0, bug

#345 Credential through file
  cmd/main.go
  pkg/cmd/list_credential.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/credential/settings.go
  pkg/rtutorial/finder_test.go
Labels: 2.0.0, feature

#354 Fix notice
  NOTICE.md
Labels: 2.0.0

#353 Added information about legacy version 1.0.0
  README.md
Labels: 2.0.0, improvement

#355 [Fix] init warning msg
  pkg/cmd/init.go
Labels: 2.0.0, bug

#357 [Fix] lint
  pkg/formula/repo.go
Labels: 2.0.0, bug

#361 [FIX] Add repo with the commons name
  pkg/cmd/add_repo.go
  pkg/formula/repo.go
Labels: 2.0.0, bug

#371 [FIX] stable version URL
  pkg/cmd/root.go
Labels: 1.0.0, bug, priority:high, single, team

#375 [FEATURE] Create interface for metrics
  pkg/metric/metric.go
Labels: 2.0.0, feature

#378 [ENHANCEMENT] build formula tutorial
  pkg/cmd/build_formula.go
Labels: 2.0.0, improvement

#395 [FEATURE] Add EMAIL to provider variables
  pkg/credential/settings.go
  pkg/credential/settings_test.go
Labels: 2.0.0, feature, improvement

#394 [FEATURE] add metrics command
  cmd/main.go
  pkg/cmd/metrics.go
  pkg/cmd/metrics_test.go
  pkg/cmd/set_credential_test.go
  pkg/metric/metric.go
  pkg/stream/mocks/mock.go
Labels: feature

#400 Improves inputListCustomMock to use a custom function
  pkg/cmd/add_repo_test.go
  pkg/cmd/metrics_test.go
  pkg/cmd/mocks_test.go
  pkg/cmd/set_credential_test.go
  pkg/cmd/set_priority_test.go
Labels: 2.0.0, improvement

#401 [ENHANCEMENT] Hello world formula command in README
  README.md
Labels: 2.0.0, improvement

#405 Metrics check
  cmd/main.go
  pkg/cmd/metrics.go
  pkg/cmd/metrics_test.go
  pkg/metrics/checker.go
  pkg/metrics/checker_test.go
  pkg/metrics/metric.go
  pkg/metrics/user_id_generator.go
  pkg/metrics/user_id_generator_test.go
  pkg/stream/mocks/mock.go
Labels: improvement, ready-for-review

#420 Adds question about metrics in init
  cmd/main.go
  functional/init/init_feature.json
  functional/runner_unix.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
Labels: 2.0.0, feature, ready-for-review

#430 Add functional test for list
  functional/core/core_feature.json
  functional/core/core_integration_test.go
  functional/runner.go
  functional/scaffold/scaffold_integration_test.go
Labels: 2.0.0, ready-for-review

#429 Collector function for metrics
  pkg/api/api.go
  pkg/metric/checker_test.go
  pkg/metric/data_collector.go
  pkg/metric/data_collector_test.go
  pkg/metric/grpc_sender.go
  pkg/metric/grpc_sender_test.go
  pkg/metric/http_sender.go
  pkg/metric/http_sender_test.go
  pkg/metric/metric.go
  pkg/version/version.go
Labels: feature, ready-for-review

#426 Add entry via stdin to the init command
  functional/stdin/stdin_feature.json
  functional/stdin/stdin_integration_test.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/mocks_test.go
Labels: feature, ready-for-review

#446 Fix version.sh expression
  .circleci/scripts/version.sh
Labels: bug, ready-for-review

#435 Update tutorial on stdin and add tests
  pkg/cmd/mocks_test.go
  pkg/cmd/tutorial.go
  pkg/cmd/tutorial_test.go
Labels: improvement, ready-for-review

#450 Add collect metric to the main file
  .circleci/scripts/ritchie_metric_server.sh
  Makefile
  cmd/main.go
  pkg/cmd/metrics.go
  pkg/cmd/metrics_test.go
  pkg/cmd/mocks_test.go
  pkg/metric/checker.go
  pkg/metric/checker_test.go
  pkg/metric/data_collector.go
  pkg/metric/data_collector_test.go
  pkg/metric/metric.go
Labels: feature, ready-for-review

#448 Add functional test for create
  functional/core/core_feature.json
  functional/core/core_integration_test.go
Labels: ready-for-review

#451 Formatted metric text in init command
  functional/init/init_feature.json
  functional/runner_unix.go
  pkg/cmd/init.go
Labels: feature, ready-for-review

#452 Standardized metrics command
  cmd/main.go
  pkg/api/api.go
  pkg/cmd/metrics.go
  pkg/cmd/metrics_test.go
Labels: bug

#458 Add functional test for build
  functional/core/core_feature.json
  functional/core/core_integration_test.go
Labels: ready-for-review

#465 Add functional test for tutorial
  functional/core/core_feature.json
  functional/core/core_integration_test.go
Labels: ready-for-review

#403 Mount volume of the .rit folder inside the container
  cmd/main.go
  pkg/formula/runner/runner.go
  pkg/formula/runner/runner_test.go
Labels: QA, improvement

#469 Add functional test for upgrade
  .circleci/config.yml
  functional/core/core_feature.json
  functional/core/core_integration_test.go
Labels: :heavy_check_mark: ready-for-review

#467 Adding EMAIL to GITLAB credential
  pkg/credential/settings.go
Labels: QA, feature, improvement

#423 Asking for credential during formula runtime
  cmd/main.go
  pkg/credential/finder.go
  pkg/credential/finder_test.go
  pkg/env/envcredential/env_credential.go
  pkg/env/envcredential/env_credential_test.go
Labels: :heavy_check_mark: ready-for-review, QA, improvement

#466 Fix incomprehensible error in command rit add repo
  pkg/git/github/repository.go
  pkg/git/gitlab/repository.go
Labels: :beetle: bug, :rocket: QA

#484 Duplication of letters in the command list credentials
  pkg/credential/settings.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#479 Add functional test for completion fish
  functional/core/core_feature.json
  functional/core/core_integration_test.go
Labels: :heavy_check_mark: ready-for-review, :rocket: QA

#482 Add the 'password' input type to stdin
  pkg/formula/runner/inputs.go
Labels: :beetle: bug, :rocket: QA

#454 Adding conditional steps to config prompt
  pkg/formula/formula.go
  pkg/formula/runner/inputs.go
  pkg/formula/runner/inputs_test.go
Labels: :rocket: QA, :sparkles: feature

#486 Add functional test for completion powershell
  functional/core/core_feature.json
  functional/core/core_integration_test.go
Labels: :heavy_check_mark: ready-for-review

#478 Added step to question about formula found
  pkg/cmd/build_formula.go
  pkg/cmd/build_formula_test.go
  pkg/cmd/mocks_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA
