Repository ZupIT/ritchie-cli, pull requests merged in 2020-06, with the labels that each got.

#135 [FIX] Rename field qtd to qty
  pkg/formula/formula.go
  pkg/formula/runner.go
  pkg/formula/tpl/tpl_go/tpl_go.go
Labels: bug

#133 Feature/improvements security
  .circleci/config.yml
Labels: improvement

#137 [Fix] Remove special char in prompt
  pkg/cmd/init.go
  pkg/prompt/bool.go
  pkg/prompt/email.go
  pkg/prompt/int.go
  pkg/prompt/list.go
  pkg/prompt/password.go
  pkg/prompt/text.go
  pkg/prompt/url.go
Labels: bug, priority:low, single, team

#136 [FEATURE] update templates
  pkg/cmd/create_formula.go
  pkg/formula/creator.go
  pkg/formula/tpl/tpl_go/tpl_go.go
  pkg/formula/tpl/tpl_java/tpl_java.go
  pkg/formula/tpl/tpl_node/tpl_node.go
  pkg/formula/tpl/tpl_python/tpl_python.go
  pkg/formula/tpl/tpl_shell/tpl_shell.go
Labels: feature

#138 [FIX] env runner formula
  pkg/formula/runner.go
Labels: bug

#142 [FIX] update local repo name
  pkg/cmd/create_formula.go
Labels: documentation, improvement

#145 changed folder name
  pkg/formula/creator.go
Labels: bug

#146 [Feature] color messages
  pkg/cmd/add_repo.go
  pkg/cmd/clean_repo.go
  pkg/cmd/create_formula.go
  pkg/formula/creator.go
  pkg/formula/creator_test.go
  pkg/prompt/color.go
Labels: feature

#113 [FEATURE] run formula docker
  .circleci/config.yml
  .github/ritchie-bot-config.yml
  Makefile
  cmd/single/main.go
  cmd/team/main.go
  docker-compose.yml
  go-version.sh
  pkg/api/api.go
  pkg/cmd/formula_test.go
  pkg/cmd/formulas.go
  pkg/cmd/mocks_test.go
  pkg/cmd/show_context.go
  pkg/file/fileutil/file_util.go
  pkg/formula/creator.go
  pkg/formula/default_pre_runner.go
  pkg/formula/default_runner.go
  pkg/formula/default_runner_test.go
  pkg/formula/default_setup.go
  pkg/formula/default_setup_test.go
  pkg/formula/docker_pre_runner.go
  pkg/formula/docker_runner.go
  pkg/formula/docker_runner_test.go
  pkg/formula/formula.go
  pkg/formula/formula_test.go
  pkg/formula/inputs.go
  pkg/formula/inputs_test.go
  pkg/formula/post_run.go
  pkg/formula/runner.go
  pkg/http/headers/headers.go
  run-tests-ci.sh
  run-tests.sh
  testdata/stubby4j/integrations.yml
  testdata/stubby4j/response.zip
  wait-for-it.sh
Labels: feature

#162 Feature/colors
  pkg/cmd/add_repo.go
  pkg/cmd/clean_repo.go
  pkg/cmd/create_formula.go
  pkg/cmd/delete_context.go
  pkg/cmd/delete_repo.go
  pkg/cmd/init.go
  pkg/cmd/list.go
  pkg/cmd/login.go
  pkg/cmd/logout.go
  pkg/cmd/root.go
  pkg/cmd/set_context.go
  pkg/cmd/set_credential.go
  pkg/cmd/show_context.go
  pkg/formula/creator.go
  pkg/formula/default_setup.go
  pkg/formula/inputs.go
  pkg/prompt/color.go
  pkg/stdin/stdin.go
Labels: feature

#166 [FIX] trailing slashes removed
  .gitignore
  pkg/server/setter.go
  pkg/server/setter_test.go
Labels: bug

#175 cleanup, refactor and improvements regarding beta and nightly version
  .circleci/scripts/beta_version_gen.sh
  .circleci/scripts/credentials.sh
  .circleci/scripts/nightly_version_gen.sh
  .circleci/scripts/ritchie_server.sh
  .circleci/scripts/version.sh
Labels: feature

#165 Feature/rit upgrade
  cmd/single/main.go
  cmd/team/main.go
  go.mod
  pkg/cmd/root.go
  pkg/cmd/upgrade.go
  pkg/cmd/upgrade_test.go
  pkg/file/fileutil/service.go
  pkg/upgrade/manager.go
  pkg/upgrade/manager_test.go
  pkg/upgrade/updater.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/version/resolver.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: feature

#180 [FEATURE] Build formula with Ritchie-cli
  .circleci/scripts/bucket.sh
  .circleci/scripts/version.sh
  Makefile
  cmd/single/main.go
  cmd/team/main.go
  go.mod
  pkg/api/api.go
  pkg/cmd/build.go
  pkg/cmd/build_formula.go
  pkg/cmd/formulas.go
  pkg/formula/builder/build.go
  pkg/formula/builder/build_test.go
  pkg/formula/formula.go
  pkg/formula/watcher/watcher.go
  pkg/formula/watcher/watcher_test.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_manager.go
  pkg/formula/workspace/workspace_manager_test.go
  pkg/slice/sliceutil/slice_util.go
  pkg/slice/sliceutil/slice_util_test.go
  pkg/stream/dir.go
  pkg/stream/file.go
  pkg/stream/streams/stream.go
  testdata/ritchie-formulas-test.zip
Labels: feature

#194 [bug] fix completion zsh,bash
  pkg/cmd/root.go
Labels: bug

#216 [FEATURE] Adding hello world template in PHP (Issue #185)
  pkg/cmd/create_formula.go
  pkg/formula/creator.go
  pkg/formula/creator_test.go
  pkg/formula/lang.go
  pkg/formula/tpl/tpl_php/tpl_php.go
  testdata/Makefile
Labels: feature

#219 [FEATURE] Docker ritchie-server
  docker-ritchie-server/README.md
  docker-ritchie-server/data/keycloak/ritchie.json
  docker-ritchie-server/data/ldap/config.ldif
  docker-ritchie-server/data/server/create-vault-approle.sh
  docker-ritchie-server/data/server/env.sh
  docker-ritchie-server/data/server/file_config.json
  docker-ritchie-server/data/server/ritchie_server_policy.hcl
  docker-ritchie-server/data/server/wait-for-it.sh
  docker-ritchie-server/data/vault/resources/ritchie_server_policy.hcl
  docker-ritchie-server/data/vault/resources/vault.hcl
  docker-ritchie-server/docker-compose.yml
Labels: feature
