Repository ZupIT/ritchie-cli, pull requests merged in 2021-05, with the labels that each got.

#908 Adding flags, delete confirmation and new tests to delete repo
  functional/stdin/stdin_feature.json
  pkg/cmd/delete_repo.go
  pkg/cmd/delete_repo_test.go
  pkg/commands/builder.go
  pkg/formula/repo/deleter.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#913 Feature/add formula rit list formulas
  internal/mocks/mocks.go
  pkg/api/api.go
  pkg/cmd/delete_repo.go
  pkg/cmd/list.go
  pkg/cmd/list_formula.go
  pkg/cmd/list_formula_test.go
  pkg/cmd/mocks_test.go
  pkg/commands/builder.go
  pkg/formula/tree.go
  pkg/formula/tree/checker_test.go
  pkg/formula/tree/default_tree.go
  testdata/tree.zip
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#925 Fixes #914 by changing Docker's invocation command
  pkg/formula/runner/docker/pre_run.go
  pkg/formula/runner/docker/runner.go
Labels: :apple: Mac, :beetle: bug, Windows

#928 Add `Generate Patch Tag` workflow on Github Actions
  .github/workflows/generate-patch-tag.yml
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#929 Add `Open Issue Doc` workflow on Github Actions
  .github/workflows/open-issue-doc.yml
Labels: :hammer: improvement

#926 Improvement/tests with testify set env
  pkg/cmd/set_env.go
  pkg/cmd/set_env_test.go
Labels: :heavy_check_mark: ready-for-review

#930 Update metrics for input flags
  pkg/metric/data_collector.go
  pkg/metric/data_collector_test.go
  pkg/metric/metric.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#916 Support flags for the rit update repo command.
  pkg/cmd/update_repo.go
  pkg/cmd/update_repo_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#936 Update generate patch branch workflow
  .github/workflows/generate-patch-branch.yml
Labels: :hammer: improvement

#935 FIX stdout cmd on local runner
  pkg/formula/runner/local/runner.go
Labels: :beetle: bug

#938 POC - Github Action Workflow to test RIT binaries for each supported OS
  .github/workflows/test-repo-commands.yml
  testdata/gha_workflows/repo_workflow/assert1.txt
  testdata/gha_workflows/repo_workflow/assert2.txt
  testdata/gha_workflows/repo_workflow/assert3.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :racehorse: Performance

#922 Add `rit update workspace` core command
  internal/mocks/mocks.go
  pkg/api/api.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/update_workspace.go
  pkg/cmd/update_workspace_test.go
  pkg/commands/builder.go
  pkg/formula/workspace.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#942 Update rename formula test
  pkg/cmd/rename_formula_test.go
Labels: :heavy_check_mark: ready-for-review

#941 Update CHANGELOG file with 2.11.3 Release
  CHANGELOG.md
Labels: :heavy_check_mark: ready-for-review
