Repository ZupIT/ritchie-cli, pull requests merged in 2021-04, with the labels that each got.

#888 Detect new repository version
  go.mod
  pkg/api/api.go
  pkg/autocomplete/generator_test.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/formula.go
  pkg/commands/builder.go
  pkg/formula/creator/creator.go
  pkg/formula/creator/creator_test.go
  pkg/formula/repo.go
  pkg/formula/repo/list_detail_writer.go
  pkg/formula/tree/default_tree.go
  pkg/formula/tree/default_tree_test.go
  vendor/modules.txt
Labels: :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#903 Friendlier error message on update repo
  .github/CODEOWNERS
  CONTRIBUTORS
  pkg/git/bitbucket/repository.go
  pkg/git/bitbucket/repository_test.go
  pkg/git/git.go
  pkg/git/github/repository.go
  pkg/git/github/repository_test.go
  pkg/git/gitlab/repository.go
  pkg/git/gitlab/repository_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#906 Add tests with testify for delete repo
  pkg/cmd/delete_repo_test.go
Labels: :broom: chore, :heavy_check_mark: ready-for-review

#904 Testify flag refactor
  pkg/formula/input/flag/flag_test.go
  pkg/formula/input/input.go
Labels: :broom: chore, :rocket: QA

#892 Bugfix - input autocomplete
  go.mod
  vendor/github.com/JoaoDanielRufino/go-input-autocomplete/input.go
  vendor/golang.org/x/sys/unix/asm_bsd_386.s
  vendor/golang.org/x/sys/unix/asm_bsd_amd64.s
  vendor/golang.org/x/sys/unix/asm_bsd_arm.s
  vendor/golang.org/x/sys/unix/asm_bsd_arm64.s
  vendor/golang.org/x/sys/unix/asm_darwin_386.s
  vendor/golang.org/x/sys/unix/asm_darwin_amd64.s
  vendor/golang.org/x/sys/unix/asm_darwin_arm.s
  vendor/golang.org/x/sys/unix/asm_darwin_arm64.s
  vendor/golang.org/x/sys/unix/asm_freebsd_amd64.s
  vendor/golang.org/x/sys/unix/asm_freebsd_arm.s
  vendor/golang.org/x/sys/unix/asm_freebsd_arm64.s
  vendor/golang.org/x/sys/unix/asm_netbsd_386.s
  vendor/golang.org/x/sys/unix/asm_netbsd_amd64.s
  vendor/golang.org/x/sys/unix/asm_netbsd_arm.s
  vendor/golang.org/x/sys/unix/asm_netbsd_arm64.s
  vendor/golang.org/x/sys/unix/asm_openbsd_arm.s
  vendor/golang.org/x/sys/unix/asm_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_illumos_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: :beetle: bug, :rocket: QA

#912 New error message.
  pkg/formula/builder/bat.go
  pkg/formula/builder/make.go
  pkg/formula/builder/shell.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review
