Repository ZupIT/ritchie-cli, pull requests merged in 2021-01, with the labels that each got.

#816 Fix delete workspace
  internal/mocks/mocks.go
  pkg/cmd/delete_workspace.go
  pkg/cmd/delete_workspace_test.go
  pkg/commands/builder.go
  pkg/formula/builder/local.go
  pkg/formula/repo/repoutil/repoutil.go
  pkg/formula/repo/repoutil/repoutil_test.go
  pkg/formula/workspace/workspace.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#819 fixing release pipeline
  Makefile
Labels: :beetle: bug, Windows

#774 Delete credential flags
  internal/mocks/mocks.go
  pkg/cmd/cmd.go
  pkg/cmd/delete_credential.go
  pkg/cmd/delete_credential_test.go
  pkg/cmd/formula.go
  pkg/commands/builder.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#822 Added new tests to rit delete env
  pkg/cmd/delete_env_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#831 Testify on commands package
  pkg/commands/builder_test.go
Labels: :broom: chore, :rocket: QA

#826 Add flags to delete env
  pkg/cmd/delete_env.go
  pkg/cmd/delete_env_test.go
  pkg/env/finder_test.go
  pkg/env/remover.go
  pkg/env/remover_test.go
  pkg/env/setter_test.go
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#830 Removing file util package with test refactor
  internal/mocks/builder.go
  pkg/cmd/create_formula_test.go
  pkg/commands/builder.go
  pkg/file/fileutil/file_util.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: :broom: chore, :heavy_check_mark: ready-for-review, :rocket: QA

#823 feat: add bitbucket as a provider to add repos
  internal/mocks/bitbucket.go
  pkg/commands/builder.go
  pkg/git/bitbucket/bitbucket.go
  pkg/git/bitbucket/bitbucket_test.go
  pkg/git/bitbucket/repository.go
  pkg/git/bitbucket/repository_test.go
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :rocket: QA, :sparkles: feature

#827 Flags for rit add repo
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/cmd.go
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#824 Set credential flags
  pkg/cmd/cmd.go
  pkg/cmd/delete_credential.go
  pkg/cmd/delete_credential_test.go
  pkg/cmd/set_credential.go
  pkg/cmd/set_credential_test.go
  pkg/commands/builder.go
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#832 Adding flags and tests to delete workspace
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/cmd.go
  pkg/cmd/delete_credential.go
  pkg/cmd/delete_workspace.go
  pkg/cmd/delete_workspace_test.go
  pkg/commands/builder.go
  pkg/formula/repo.go
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA
