Repository ZupIT/ritchie-cli, pull requests merged in 2021-07, with the labels that each got.

#984 Update doc release workflow with `create-other-repo-branch-action`
  .github/workflows/generate-doc-release-branch.yml
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :octocat: github-actions

#954 Improve status of path on list workspace
  pkg/cmd/list_workspace.go
  pkg/cmd/list_workspace_test.go
Labels: :hammer: improvement

#986 New credential for adding private repositories with `rit add repo`
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/commands/builder.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#989 Fixes issue #987, restoring compatibility with Docker Desktop < 2.5.0 on Windows/MacOS and adding compatibility to WSL*
  pkg/formula/runner/docker/pre_run.go
Labels: :hammer: improvement, usability, 🐳 Docker

#973 Support flags to metrics command
  pkg/cmd/metrics.go
  pkg/cmd/metrics_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#1000 Add security section, files and workflow
  .github/workflows/auto-approve.yml
  README.md
  SECURITY.md
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :lock: security

#991 refactor: add workspace flag
  pkg/cmd/delete_formula.go
  pkg/cmd/rename_formula.go
  pkg/cmd/rename_formula_test.go
  pkg/formula/runner/docker/pre_run.go
  testdata/gha_workflows/formula_workflow/assert3.txt
  testdata/gha_workflows/formula_workflow/assert4.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#1002 Functional tests rit metrics
  .github/workflows/test-global-commands.yml
  testdata/gha_workflows/global_workflow/assert10.txt
  testdata/gha_workflows/global_workflow/assert8.txt
  testdata/gha_workflows/global_workflow/assert9.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review
