Repository ZupIT/ritchie-cli, pull requests merged in 2021-06, with the labels that each got.

#955 Improve - Add workflows to build binary files when pull request is opened, and add links to pr body.
  .github/workflows/build-binary-when-pr-open.yml
  .github/workflows/list-artifacts-edit-pr-body.yml
Labels: :hammer: improvement

#946 Adding mac packaging
  packaging/mac-pkg/build-macos-x64.sh
  packaging/mac-pkg/darwin/Distribution
  packaging/mac-pkg/darwin/Resources/LICENSE.txt
  packaging/mac-pkg/darwin/Resources/banner.png
  packaging/mac-pkg/darwin/Resources/conclusion.html
  packaging/mac-pkg/darwin/Resources/uninstall.sh
  packaging/mac-pkg/darwin/Resources/welcome.html
  packaging/mac-pkg/darwin/scripts/install-rit.sh
  packaging/mac-pkg/darwin/scripts/postinstall
  packaging/mac-pkg/utils/ascii_art.txt
Labels: :apple: Mac

#932 support flags - rit init
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/prompt/bool.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#956 Github Action workflow to perform functional tests for `CREDENTIAL` core commands using RIT binaries
  .github/workflows/test-credential-commands.yml
  .github/workflows/test-env-commands.yml
  .github/workflows/test-repo-commands.yml
  testdata/gha_workflows/credential_workflow/assert1.txt
  testdata/gha_workflows/credential_workflow/assert2.txt
  testdata/gha_workflows/repo_workflow/assert2.txt
  testdata/gha_workflows/repo_workflow/assert3.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :racehorse: Performance

#964 Enhancement/readme
  README.md
  docs/img/documentation-ritchie.png
  docs/img/zup-forum-topics.png
  docs/img/zup-open-source.png
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, usability

#966 Github Action workflow to perform functional tests for `GLOBAL` core commands using RIT binaries
  .github/workflows/test-credential-commands.yml
  .github/workflows/test-env-commands.yml
  .github/workflows/test-global-commands.yml
  .github/workflows/test-repo-commands.yml
  testdata/gha_workflows/global_workflow/assert1.txt
  testdata/gha_workflows/global_workflow/assert1_win.txt
  testdata/gha_workflows/global_workflow/assert2.txt
  testdata/gha_workflows/global_workflow/assert3.txt
  testdata/gha_workflows/global_workflow/assert4.txt
  testdata/gha_workflows/global_workflow/assert5.txt
  testdata/gha_workflows/global_workflow/assert6.txt
  testdata/gha_workflows/global_workflow/assert7.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :racehorse: Performance

#950 Flag support in command create formula / Create new workspace if does not exist
  internal/mocks/post_run.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/commands/builder.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#969 Update build-macos-x64.sh script removing certificate prompt
  packaging/mac-pkg/build-macos-x64.sh
Labels: :hammer: improvement

#968 Update functional tests using the `test-cli-commands-action`
  .github/workflows/test-credential-commands.yml
  .github/workflows/test-env-commands.yml
  .github/workflows/test-global-commands.yml
  .github/workflows/test-repo-commands.yml
  package-lock.json
  testdata/gha_workflows/global_workflow/assert1_win.txt
  testdata/gha_workflows/repo_workflow/assert2.txt
  testdata/gha_workflows/repo_workflow/assert3.txt
Labels: :heavy_check_mark: ready-for-review, :racehorse: Performance

#970 Github Action workflow to perform functional tests for `FORMULA` core commands using RIT binaries
  .github/workflows/test-formula-commands.yml
  pkg/cmd/rename_formula.go
  pkg/cmd/rename_formula_test.go
  testdata/gha_workflows/formula_workflow/assert1.txt
  testdata/gha_workflows/formula_workflow/assert2.txt
  testdata/gha_workflows/formula_workflow/assert3.txt
  testdata/gha_workflows/formula_workflow/assert4.txt
  testdata/gha_workflows/formula_workflow/assert5.txt
  testdata/gha_workflows/formula_workflow/assert6.txt
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :racehorse: Performance

#951 Bug Fix - When running with dockers the files created by the formulas have owner root
  .github/workflows/get-list-artifacts-and-update-pr-body.yml
  pkg/formula/builder/docker.go
  pkg/formula/runner/docker/runner.go
Labels: :beetle: bug

#974 fix: fix check for add workspace when error different than expected
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, priority:high

#975 Add section about `functional testing` on Developer Guide
  DEVELOPER_GUIDE.md
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#976 Add workflow to generate new doc release branch automatically based on `ritchie-cli` release tag
  .github/workflows/generate-doc-release-branch.yml
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review

#977 refactor: validate workspace name
  pkg/cmd/add_workspace.go
  pkg/cmd/add_workspace_test.go
  pkg/cmd/create_formula.go
  pkg/cmd/create_formula_test.go
  pkg/cmd/delete_formula.go
  pkg/cmd/delete_formula_test.go
  pkg/commands/builder.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, priority:high

#978 Update mac-pkg script and files
  DEVELOPER_GUIDE.md
  packaging/mac-pkg/build-macos-x64.sh
  packaging/mac-pkg/darwin/Resources/LICENSE.txt
  packaging/mac-pkg/darwin/Resources/banner.png
  packaging/mac-pkg/darwin/Resources/conclusion.html
  packaging/mac-pkg/darwin/Resources/uninstall.sh
  packaging/mac-pkg/darwin/Resources/welcome.html
Labels: :apple: Mac, :hammer: improvement, :heavy_check_mark: ready-for-review, :lock: security, usability
