Repository ZupIT/ritchie-cli, pull requests merged in 2021-03, with the labels that each got.

#872 Improved error msg on invalid value on list input
  pkg/formula/input/flag/flag.go
  pkg/formula/input/flag/flag_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#876 test: github testify
  pkg/git/github/github.go
  pkg/git/github/github_test.go
  pkg/git/github/repository.go
  pkg/git/github/repository_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#879 Adding safety check to workspace add
  pkg/cmd/add_workspace.go
  pkg/formula/workspace/workspace.go
  pkg/formula/workspace/workspace_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#882 Multiselect flag support
  pkg/cmd/formula.go
  pkg/formula/formula_test.go
  pkg/formula/input/flag/flag.go
  pkg/formula/input/flag/flag_test.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#878 Add new fields to enable cache in the repositories
  pkg/cmd/create_formula_test.go
  pkg/cmd/list_repo.go
  pkg/cmd/list_repo_test.go
  pkg/commands/builder.go
  pkg/formula/builder/local_test.go
  pkg/formula/repo.go
  pkg/formula/repo/adder.go
  pkg/formula/repo/adder_test.go
  pkg/formula/repo/list_adder_test.go
  pkg/formula/repo/list_updater_test.go
  pkg/formula/repo/list_write_creator.go
  pkg/formula/repo/list_write_creator_test.go
  pkg/formula/repo/updater.go
  pkg/formula/repo/updater_test.go
  pkg/formula/tree/generator.go
Labels: :heavy_check_mark: ready-for-review, :racehorse: Performance, :sparkles: feature

#884 Changing conditional to only return an error when the conditional input variable does not exist in the config.json variable list
  pkg/formula/input/flag/flag.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#874 Adding feature containsAny, containsAll, containsOnly, notContainsAny and notContainsAll in conditional options
  pkg/formula/input/flag/flag.go
  pkg/formula/input/flag/flag_test.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :sparkles: feature

#894 Correction of input flags with parameter not required.
  pkg/formula/input/flag/flag.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review

#898 New ritchiecli-user.msi
  .circleci/config.yml
  .circleci/scripts/gen-win.ps1
  Makefile
  packaging/windows/ritchie-admin-wix-templates/LicenseAgreementDlg_HK.wxs
  packaging/windows/ritchie-admin-wix-templates/WixUI_HK.wxs
  packaging/windows/ritchie-admin-wix-templates/product.wxs
  packaging/windows/ritchie-user-wix-templates/LicenseAgreementDlg_HK.wxs
  packaging/windows/ritchie-user-wix-templates/WixUI_HK.wxs
  packaging/windows/ritchie-user-wix-templates/product.wxs
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature, Windows
