Repository ZupIT/ritchie-cli, pull requests merged in 2021-02, with the labels that each got.

#840 Fix/readme repo template
  testdata/repos/commons/templates/create_formula/root/README.md
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :rocket: QA, deprecation

#834 Create translation for init command
  .golangci.yml
  Makefile
  cmd/main.go
  internal/pkg/config/config.go
  internal/pkg/i18n/i18n.go
  internal/pkg/i18n/i18n_test.go
  internal/pkg/i18n/translations.go
  pkg/cmd/init.go
  pkg/cmd/mocks_test.go
  pkg/cmd/upgrade.go
  pkg/formula/repo/priority_setter_test.go
  resources/i18n/en.toml
  resources/i18n/pt_BR.toml
Labels: :heavy_check_mark: ready-for-review, :sparkles: feature

#838 Adds a simple fix to the help menu
  pkg/cmd/add.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#836 Set formula runner flags
  pkg/cmd/set_formula_runner.go
  pkg/cmd/set_formula_runner_test.go
  pkg/commands/builder.go
  pkg/formula/runner/config_runner.go
  pkg/formula/runner/config_runner_test.go
  pkg/formula/runner/post_run_test.go
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#842 fix: required multiselect
  pkg/formula/input/prompt/prompt_test.go
  pkg/prompt/multiselect.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#843 Support for list input type
  internal/mocks/credential.go
  internal/mocks/error.go
  internal/mocks/mocks.go
  pkg/cmd/add_repo_test.go
  pkg/cmd/create_formula_test.go
  pkg/commands/builder.go
  pkg/formula/input/input.go
  pkg/formula/input/prompt/prompt.go
  pkg/formula/input/prompt/prompt_test.go
  pkg/formula/runner/docker/runner_test.go
  pkg/formula/runner/local/runner_test.go
  pkg/formula/workspace/workspace_test.go
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#850 Fix merge conflict between PRs
  pkg/formula/input/prompt/prompt_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#829 Fix- Print error messages in pre builder
  internal/mocks/formula.go
  internal/mocks/runner.go
  internal/mocks/workspace.go
  pkg/formula/runner.go
  pkg/formula/runner/executor.go
  pkg/formula/runner/executor_test.go
  pkg/formula/runner/pre_run_builder.go
  pkg/formula/runner/pre_run_builder_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#848 refactor: deprecated dynamic input
  internal/mocks/post_run.go
  pkg/formula/runner/config_runner_test.go
  pkg/formula/runner/post_run.go
  pkg/formula/runner/post_run_test.go
Labels: :books: documentation, :heavy_check_mark: ready-for-review, :rocket: QA, deprecation

#841 Add step to check de latest version on rit add repo and entry by flags
  pkg/cmd/add_repo.go
  pkg/cmd/add_repo_test.go
  pkg/formula/repo.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#846 Tutorial flags
  pkg/cmd/create_formula_test.go
  pkg/cmd/tutorial.go
  pkg/cmd/tutorial_test.go
  pkg/commands/builder.go
  pkg/rtutorial/find_setter.go
  pkg/rtutorial/finder.go
  pkg/rtutorial/finder_test.go
  pkg/rtutorial/setter.go
  pkg/rtutorial/setter_test.go
  pkg/rtutorial/tutorial.go
Labels: :books: documentation, :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#864 Fixing delete credential empty fields bug
  pkg/cmd/delete_credential.go
Labels: :beetle: bug

#862 [BUGFIX] - Fix build with build.sh
  pkg/formula/runner/local/pre_run.go
Labels: :beetle: bug, :rocket: QA

#856 test: gitlab testify
  internal/mocks/git.go
  pkg/git/gitlab/gitlab_test.go
  pkg/git/gitlab/repository.go
  pkg/git/gitlab/repository_test.go
Labels: :hammer: improvement, :heavy_check_mark: ready-for-review, :rocket: QA

#866 Update repo fix
  pkg/cmd/update_repo.go
  pkg/cmd/update_repo_test.go
Labels: :beetle: bug, :heavy_check_mark: ready-for-review, :rocket: QA

#868 Update input flag README file
  README.md
Labels: :books: documentation
